# Generated by Django 5.0.7 on 2024-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
